### PR TITLE
Issue 178 - Initial attempt at moving to heavier resource providers.

### PR DESCRIPTION
**Pull request by cyberswat**
This illustrates moving towards a heavier weight resource provider for both apache_web_app and apache_site.  It's a significant change and I'll continue working it if the direction is desired.

This touches three major areas: the apache_web_app and apache_site LWRPs, the web_app template, and the associated items in the embedded apache2_test cookbook.

I would still need to refactor the apache2_test::mod_perl, apache2_test::broken_conf ... and possibly the recipes commented out in the .kitchen.yml (apache2_test::mod_auth_openid, apache2_test::mod_authnz_ldap, apache2_test::mod_dav_svn, apache2_test::mod_perl, apache2_test::mod_proxy_ajp).

### CODE REVIEW

**Comment by svanzoest** [comment]
I will want to see how this maps to the newer custom resources #414

**Comment by joelhandwell** [comment]
@cyberswat do you still working on this?

**Comment by cyberswat** [comment]
I am not.  We used this for a long time in production and have since moved on to other approaches.

**Comment by svanzoest** [comment]
Thanks for letting us know.

**Pull request closed without merging**
