### PR TITLE
Major rewrite to put many module configs into attributes

### PR DESCRIPTION
**Pull request by jorhett**
This is a major rewrite to put many module configs into attributes.

Furthermore this consistent logic made it easy to create a "default recipe" for modules which don't need special hacks. Many of the mod_ recipes can be removed after shifting some parts of them into attributes.

### CODE REVIEW

**Comment by jorhett** [comment]
Hey, anything I can do to help move this along?

**Comment by svanzoest** [comment]
Hi @jorhett 
I am looking this over, but having this PR pass the built would be a good step.

I wonder if we can shorten that `has_recipe` hash, as that seems prone for typos and easy to forget adding it to that list when a new module gets added.

**Comment by jorhett** [comment]
Okay, so I'm happy to keep developing towards a major version cut with you, but the hack/slash we have to do to work around the lack of amazon support in apache2 is frustrating, and 5-7x the size of these patches.

How can we move forward to fix the immediate problems with amazon support and get those changes into the supermarket?

**Comment by jorhett** [comment]
"I wonder if we can shorten that has_recipe hash, as that seems prone for typos and easy to forget adding it to that list when a new module gets added."

I can't parse this sentence into an actionable statement. What do you think needs shortened? The name of the hash? The entries? ...?

**Comment by svanzoest** [comment]
I agree. It would be great if we could just have Amazon Linux be more consistent, so we do not need to put all these conditionals in.

>> "I wonder if we can shorten that has_recipe hash, as that seems prone for typos and easy to forget 
>> adding it to that list when a new module gets added."

> I can't parse this sentence into an actionable statement. What do you think needs shortened? The 
> name of the hash? The entries? ...?

I was more thinking that we should see if we could it in a way that made it easier to review at a glance and therefore make it less likely that we would forget to update it. There can be many moving parts in a cookbook like this, and it is important to focus on consistency and ensuring we do not break all the platforms we support. 

In the chefspec/serverspec tests we have arrays `modules_with_config` and `modules_without_config` which is another way to approach this. That is error prone in slightly different ways, such as adding a module to both, etc. The goal is to avoid a maintenance headache and minimize the chance that a typo could get through in a release. I would rather have it fail hard during chefspec then for it to slip by.

**Comment by jorhett** [comment]
Amazon Linux is quite consistent. You can install any of PHP 5.3, 5.5, or 5.6. The prefix changes with each version.

php-      = php 5.3
php55-  = php 5.5
php56-  = php 5.6

This kind of prefixing ensures consistency and lack of surprise. Many/most apps fail when changing PHP versions without warning. Having php- suddenly install php 5.6 would definitely cause major problems.

**Comment by jorhett** [comment]
As for "easier to review at a glance" -- still seems to be subjective, and I'm not a mind reader.  I consider my Pull requests to be suggestions. Trust me that I often refactor Pulls I get from others to my own desires, I really don't care if you do that to mine. But asking me to figure how what naming style will make you happy... isn't really something you should bounce back to me. Adjust to make yourself happy :D

**Comment by svanzoest** [comment]
No worries. I'll take a look at this when I find some time and get it merged in.

**Comment by svanzoest** [comment]
The more I look over this, I think there are some interesting ideas in here. However, this seems to not have any test updates nor does it seem to address other platforms.

Thanks for your work on this and will take it into account in future improvements such as #414

**Comment by jorhett** [comment]
Frankly, asking me to do a lot of work to make it work the way you want and then ignoring it for A YEAR then closing it because it doesn't meet some guideline you didn't mention... wow.

You just love wasting people's time, don't you?

**Pull request closed without merging**
