### PR TITLE
Use systemd on RHEL/CentOS 7

### PR DESCRIPTION
**Pull request by joerocklin**
On a minimal CentOS 7 system using just systemd (without initscripts installed) the service setup fails because `/sbin/service` isn't installed. The systemd service definitions on CentOS 7 correctly use the `graceful` command for the reload process.

### CODE REVIEW

**Comment by svanzoest** [comment]
This looks good to me, can you update the serverspec and chefspec to match?

**Comment by drpebcak** [comment]
This will break Amazon Linux support #302 

Amazon Linux does not use systemd, but it does return `rhel` for `platform_family`

**Comment by svanzoest** [comment]
@drpebcak yes leaving that to chef is better rather than hard coding it.

**Comment by joerocklin** [comment]
Does RHEL/etc < 7 or Amazon need the reload command defined this way external to the package-provided init scripts? Should all of the case statements just be removed?

**Comment by drpebcak** [comment]
I believe the `Chef::Provider::Service::Init::Redhat` class still looks for /sbin/service... not 100% sure though.

**Comment by svanzoest** [comment]
@joerocklin this is because redhat (and fedora) do not use `graceful`, but rather use `restart`. See #160 among others. It seems like they fixed it in RHEL7, which means we can guard it and only use it on lower versions. 

We can not decide upon a server provider and just leave that decision to chef itself. It is much better at that and it is important for that to be consistent across cookbooks.

**Comment by svanzoest** [comment]
where are with this one @drpebcak ?

**Comment by drpebcak** [comment]
Not sure what we wanted to do for this. We could say:

```
if node['platform_version'].to_f < 7.0 || node['platform'] == 'amazon' 
  reload_command '/sbin/service httpd graceful'
else
  provider Chef::Provider::Service::Systemd
end
```

**Comment by svanzoest** [comment]
@drpebcak I wouldn't even specify the provider, just let chef handle that.

```ruby
if node['platform_version'].to_f < 7.0 || node['platform'] == 'amazon' 
  reload_command '/sbin/service httpd graceful'
end
```

**Comment by drpebcak** [comment]
@svanzoest would that work? I thought chef only recognizes one provider per platform (https://github.com/chef/chef/issues/1717). I think we would still have to override it if we wanted to use systemd.

**Comment by drpebcak** [comment]
I'm not sure if [this](https://github.com/chef/chef/pull/1596) was implemented yet either, but this could also potentially fix this problem.

**Comment by svanzoest** [comment]
@drpebcak It was added in chef 12 and chef-client 3.8.2 (via https://github.com/opscode-cookbooks/chef-client/pull/190)

**Comment by drpebcak** [comment]
Do you think we could let newer chef releases pick the provider automatically, but hard code it in some places for backwards compatibility? 

I think that'd be the best way to go.

**Comment by svanzoest** [comment]
I guess we can but I do not know what we would hardcode and what it would buy us. This really not a cookbook issue as each cookbook would have the same issue.

**Pull request merged**
