### PR TITLE
parametarise AccessFileName, which defaults to .htaccess

### PR DESCRIPTION
**Pull request by joelhandwell**

### CODE REVIEW

**Comment by svanzoest** [comment]
Hi,

Thanks for this. Do we want to add some chefspec/serverspec tests to ensure that the security rules work? I think it would be pretty scary if we leave a whole here.

**Comment by svanzoest** [comment]
Did we ever end up writing any tests for this? I'd like to pull it in, but want to make sure we have test coverage.

**Comment by joelhandwell** [comment]
@svanzoest 
chefspec: check if template generate proper config file for default access file name (.htaccess) and custom access file name (.customaccess)

serverspec: check if apache config file contain access file name 

Please review. Thank you.

**Comment by svanzoest** [comment]
:+1: merged.

**Pull request merged**
