### PR TITLE
Ensure we grab Amazon's mod24_ packages.

### PR DESCRIPTION
**Pull request by jorhett**
Grab Amazon's renamed packages when using 2.4 on amazon linux

### CODE REVIEW

**Comment by svanzoest** [comment]
We should try to abstract this at a higher level so we do not need to change every single recipe. Maybe we need to create a new attribute that we can conditionally set.

**Comment by svanzoest** [comment]
Maybe something like `node['apache']['mod_prefix'] = 'mod24_'`

**Comment by jorhett** [comment]
I was thinking about that, but there's two things we need to track:

1. module prefix
2. whether or not to install the package -- as it seems it's not necessary except on Amazon?
3. the mod prefix would be rhel family only

**Comment by jorhett** [comment]
I dunno, look at recipes/mod_perl.rb and I think you'll see that the prefix idea will be tricky

**Comment by jorhett** [comment]
Okay, I just spent several hours making this work. Take a look at https://github.com/svanzoest-cookbooks/apache2/pull/341 where I've moved much of the module config into attributes, and given you a default recipe idea which will allow you to remove many of the mod_ recipes.

This is fairly major work, but it's both simple and powerful. There's some followup work to reduce many of the mod_ recipes into attributes, but I've done the brunt of the work for you.

**Comment by svanzoest** [comment]
Thanks for this! It is much appreciated.

**Comment by svanzoest** [comment]
I am going to close this in favor of #341

**Pull request closed without merging**
